SELECT
    CLIENT_ID,
    SUM(CASE WHEN PRODUCTS.PRODUCT_TYPE = 'MEUBLE' THEN TRANSACTIONS.PROD_PRICE * TRANSACTIONS.PROD_PRICE ELSE 0 END) AS VENTES_MEUBLE,
    SUM(CASE WHEN PRODUCTS.PRODUCT_TYPE = 'DECO' THEN TRANSACTIONS.PROD_PRICE * TRANSACTIONS.PROD_PRICE ELSE 0 END) AS VENTES_DECO
FROM
    TRANSACTIONS
JOIN
    PRODUCTS ON TRANSACTIONS.PROD_ID = PRODUCTS.PRODUCT_ID
WHERE
    TRANSACTIONS.DATE BETWEEN '2019-01-01' AND '2019-12-31'
    AND PRODUCTS.PRODUCT_TYPE IN ('MEUBLE', 'DECO')
GROUP BY
    CLIENT_ID
ORDER BY
    CLIENT_ID;
